apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: findings-tracker
  namespace: findings-tracker
spec:
  podSelector:
    matchLabels:
      app: findings-tracker
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 3000
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
